version: "3"
services:

  nginx:
    build:
      context: devops/nginx/
    container_name: nginx
    ports:
      - "8003:80"
    volumes:
      - .:/app
      - ./devops/nginx/default-dev.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: devops/php/
      dockerfile: Dockerfile
    container_name: php
    ports:
      - "9300:9000"
    volumes:
      - .:/app
      - ./devops/php/assets/php-development.ini:/usr/local/etc/php/conf.d/additional.ini
    environment:
     - DOCKER_NAME=docker_php

